services:
  app:
    build:
      context: .
    container_name: pool-manager
    ports:
      - "8000:80"       # http://localhost:8000
    volumes:
      - ./:/var/www/html:cached
    environment:
      APP_ENV: dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pool-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
