services:
  app:
    build:
      context: .
    container_name: pool-manager
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:delegated   # code seulement
      - symfony_cache:/var/www/html/var/cache
      - symfony_logs:/var/www/html/var/log
      - symfony_vendor:/var/www/html/vendor
      # si tu as du front :
      - node_modules:/var/www/html/node_modules
    environment:
      APP_ENV: dev
      APP_DEBUG: 1a
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pool-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  symfony_cache:
  symfony_logs:
  symfony_vendor:
  node_modules: