services:
  app:
    build:
      context: .
    container_name: pool-manager
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated   # code seulement
      - symfony_cache:/var/www/html/var/cache
      - symfony_logs:/var/www/html/var/log
      - symfony_vendor:/var/www/html/vendor
      # si tu as du front :
      - node_modules:/var/www/html/node_modules
    environment:
      APP_ENV: dev
      APP_DEBUG: 1a
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  db:
    image: mysql:8.0
    container_name: pool-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  dbdata:
  symfony_cache:
  symfony_logs:
  symfony_vendor:
  node_modules:
