name: Generate Changelog for Symfony Project

on:
  release:
    types: [created, edited]  # Déclenche sur création/édition d'une release manuelle
  workflow_dispatch:  # Permet de lancer manuellement depuis l'onglet Actions (pour tester)

permissions:
  contents: write  # Essentiel pour committer et pousser CHANGELOG.md

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Récupère l'historique complet pour analyser les commits/tags

      - name: Debug - List tags and recent commits
        run: |
          echo "=== Tags disponibles ==="
          git tag --list --sort=-version:refname | head -5
          echo "=== 5 derniers commits ==="
          git log --oneline -5
          PREV_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1) 2>/dev/null || echo "")
          echo "Tag actuel (si release): ${{ github.event.release.tag_name || 'Aucun (test manuel)' }}"
          echo "Tag précédent: $PREV_TAG"

      - name: Install git-cliff (dernière version stable)
        run: |
          # Télécharge la dernière release x86_64-linux (plus robuste que v1.5.0 fixe)
          LATEST_VERSION=$(curl -s https://api.github.com/repos/orhun/git-cliff/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          curl -L https://github.com/orhun/git-cliff/releases/download/${LATEST_VERSION}/git-cliff-${LATEST_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv git-cliff-${LATEST_VERSION}-x86_64-unknown-linux-gnu/git-cliff /usr/local/bin/
          git-cliff --version  # Vérifie l'installation

      - name: Generate Changelog
        id: changelog
        run: |
          TAG_NAME="${{ github.event.release.tag_name || 'unreleased' }}"  # Fallback pour test manuel
          PREV_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1) 2>/dev/null || echo "")
          FROM_RANGE="${PREV_TAG:-HEAD~10}"  # Range par défaut

          # Crée CHANGELOG.md si inexistant
          if [ ! -f CHANGELOG.md ]; then
            echo "# PoolManager Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

          # Essaie git-cliff (nécessite conventional commits pour du contenu riche)
          git-cliff --output CHANGELOG.md --prepend --tag "$TAG_NAME" --from "$FROM_RANGE" --config cliff.toml || {
            echo "git-cliff a échoué ou généré vide ; fallback vers git log basique"
            # Alternative basique : Ajoute une section avec git log
            echo "## [$TAG_NAME] - $(date +%Y-%m-%d)" >> CHANGELOG.md
            git log "$FROM_RANGE"..HEAD --pretty=format:"- %s (%an, %ar)" >> CHANGELOG.md || echo "- Pas de nouveaux commits" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          }

          # Affiche un aperçu pour debug
          echo "=== Aperçu CHANGELOG.md ==="
          cat CHANGELOG.md | head -20

      - name: Commit and Push Changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(changelog): update CHANGELOG.md for ${{ github.event.release.tag_name || 'unreleased' }}"
          file_pattern: CHANGELOG.md
          branching_mode: existing  # Met à jour la branche actuelle (main)
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
